apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - protocol: TCP
      name: nginx
      port: 80
      nodePort: 31080
    - protocol: TCP
      name: multitool
      port: 1080
      nodePort: 32080