apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  selector:
    app: nginx-multitool
  ports:
    - protocol: TCP
      name: nginx
      port: 80
    - protocol: TCP
      name: multitool
      port: 8080